name: mmoGroup
main: mmo.Group.MMOGroup
version: 0.1
website: http://forums.bukkit.org/threads/
author: Rycochet <rycochet@rycochet.com>
depend: [Spout,mmoCore]

description: Provide a grouping API for factions, classes, races etc.
