name: mmoGroup
version: ${releaseVersion}.${buildNumber}
description: Provides a grouping API for factions, classes, races etc.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Group.MMOGroup
depend: [Spout, mmoCore]
